In [1]:
import pandas as pd
import requests

### 1) RCA in the United States (2018)
Calculates RCA metric of exported products by the United States in 2018.

It uses BACI 92 (**cube=trade_i_baci_a_92**), and products at HS4 level (**rca=Exporter Country,HS4,Trade Value**). 

Given the cube's structure, we used **alias=Country,HS4** because the drilldown called _Exporter Country_ returns a column called _Country_.

For calculating the initial RCA matrix, we removed small Countries with less than 1,000,000,000 and products with less than 500,000,000. All those metrics are based on **Trade Value**. (**&threshold=Country:1000000000,HS4:500000000**).

For filtering USA, we used **filter_Country=nausa**.


API:

```
https://oec.world/api/stats/rca?cube=trade_i_baci_a_92&rca=Exporter Country,HS4,Trade Value&Year=2018&alias=Country,HS4&threshold=Country:1000000000,HS4:500000000&filter_Country=nausa
```

In [2]:
data = requests.get("https://oec.world/api/stats/rca?cube=trade_i_baci_a_92&rca=Exporter Country,HS4,Trade Value&Year=2018&alias=Country,HS4&threshold=Country:1000000000,HS4:500000000&filter_Country=nausa")
df1 = pd.DataFrame(data.json()["data"])
df1.head()

,Country ID,HS4 ID,Trade Value RCA,Trade Value,Country,HS4
0,nausa,10101,1.875769,4.197009e+08,United States,Horses
1,nausa,10102,0.375366,2.821229e+08,United States,Bovine
2,nausa,10103,0.068019,2.064376e+07,United States,Pigs
3,nausa,10104,0.019817,2.667579e+06,United States,Sheep and Goats
4,nausa,10105,0.870943,2.238879e+08,United States,Poultry

### 2) Top 10 Export Opportunities in Chile (2018)
Calculates Relatedness measure of exported products by Chile in 2018.

It uses BACI 96 (**cube=trade_i_baci_a_96**), and products at HS6 level (**rca=Exporter Country,HS6,Trade Value**). 

Given the cube's structure, we used **alias=Country,HS6** because the drilldown called _Exporter Country_ returns a column called _Country_.

For calculating the initial RCA matrix, we removed small Countries with less than 1,000,000,000 and products with less than 500,000,000. All those metrics are based on **Trade Value**. (**&threshold=Country:1000000000,HS6:500000000**).

For filtering Chile, we used **filter_Country=sachl**.

Finally, using sort and limit as options: `&options=sort:desc,limit:10`, the endpoint returned the top-10 products with highest Relatedness values.

```
https://oec.world/api/stats/relatedness?cube=trade_i_baci_a_96&rca=Exporter Country,HS6,Trade Value&Year=2018&alias=Country,HS6&threshold=Country:1000000000,HS6:500000000&filter_Country=sachl&parents=true&options=sort:desc,limit:10
```

In [3]:
data = requests.get("https://oec.world/api/stats/relatedness?cube=trade_i_baci_a_96&rca=Exporter Country,HS6,Trade Value&Year=2018&alias=Country,HS6&threshold=Country:1000000000,HS6:500000000&filter_Country=sachl&parents=true&options=sort:desc,limit:10")
df1 = pd.DataFrame(data.json()["data"])
df1.head()

,Country ID,HS6 ID,Trade Value Relatedness,Trade Value,Continent,Country,Continent ID,Section,HS2,HS4,HS6,Section ID,HS2 ID,HS4 ID,Trade Value RCA
0,sachl,1020442,0.293177,2.562605e+07,South America,Chile,sa,Animal Products,Meat and edible meat offal,"Meat of sheep or goats, fresh, chilled or frozen","Sheep cuts, bone in, frozen",1,102,10204,2.073186
1,sachl,5260111,0.207184,7.313908e+08,South America,Chile,sa,Mineral Products,"Ores, slag and ash","Iron ores and concentrates, roasted iron pyrites","Iron Ore And Concentrates, Not Agglomerated",5,526,52601,2.249715
2,sachl,11510111,0.201963,1.454955e+07,South America,Chile,sa,Textiles,"Wool, fine or coarse animal hair; horsehair ya...","Wool, not carded or combed","Shorn Wool, Greasy (Including Fleece",11,1151,115101,0.934646
3,sachl,5261610,0.194719,1.696917e+07,South America,Chile,sa,Mineral Products,"Ores, slag and ash",Precious metal ores and concentrates,Silver Ores And Concentrates,5,526,52616,1.897904
4,sachl,1030310,0.165198,7.583175e+08,South America,Chile,sa,Animal Products,"Fish and crustaceans, molluscs and other aquat...","Fish, frozen, whole","Fish; Pacific salmon, (oncorhynchus nerka/gorb...",1,103,10303,85.716340

### 1) ECI subnational - China
Calculate ECI for chinese province on 2019. It's based on Exports of each province (**Trade Flow=2**), and it compares exports level with the world on 2018 (**method=subnational**). Filters small countries, and products.

All the query parameters that include "Right" are related with the World cube (in this case **trade_i_baci_a_92**).

It includes **ECI Ranking** column (using "ranking=true").

Finally, **eciThreshold=Subnat Geography:10** means that you want to filter **Subnat Geography** with less than 10 products with RCA > 1.

In [4]:
data = requests.get("https://oec.world/api/stats/eci?cube=trade_s_chn_m_hs&rca=Subnat Geography,HS4,Trade Value&Year=2019&method=subnational&ranking=true&Trade Flow=2&cubeRight=trade_i_baci_a_92&rcaRight=Exporter Country,HS4,Trade Value&YearRight=2018&aliasRight=Country,HS4&threshold=CountryRight:1000000000,HS4Right:500000000,Subnat+Geography:100000000&eciThreshold=Subnat+Geography:10")
df1 = pd.DataFrame(data.json()["data"])
df1.head()

,Subnat Geography ID,Trade Value ECI,Trade Value ECI Ranking,Subnat Geography
0,50,0.386945,1,Chongqing
1,31,0.354050,2,Shanghai Province
2,32,0.338404,3,Jiangsu Province
3,11,0.282846,4,Beijing
4,61,0.276943,5,Shaanxi Province